Issue#6
fiddenmar/pybico_crf pull request #26
Opened 2017-05-02 07:26 UTC by fareweller

Функционал реализован. Хотя мне не очень нравится дублирования, я бы вынес дублирующуюся часть в отдельную подфункцию, или изначально реализовал её в виде парсинга массива, а не одной строки.

2017-05-02 10:36 UTC, loshca requested changes
1) исключение ловишь неправильно
2) порядок параметров изменит результат выполнения
3) дублирование кода
4) stringList? xD

2017-05-02 10:36 UTC, loshca commented on pybico_crf.py
> +				except getopt.GetoptError:
что-то у меня большие сомнения, что GetoptError ловит ошибки от open @fareweller

2017-05-02 10:36 UTC, loshca commented on pybico_crf.py
> +			elif opt == '-f':
а ситуация, когда "-l" параметр окажется позже, чем "-f"? @fareweller

2017-05-02 15:37 UTC, fiddenmar requested changes

2017-05-02 15:37 UTC, fiddenmar commented on README.md
>  Requirements:
Этот коммит не имеет отношения к реализуемой задаче, его нужно отсюда убрать.

2017-05-02 15:37 UTC, fiddenmar commented on pybico_crf.py
> +					pred = predict_one(stringList[i])
Жесткая копипаста.

2017-05-02 15:37 UTC, fiddenmar commented on pybico_crf.py
> +						db.add([publication])
Сюда нужно передавать весь массив обработанных библиографических записей.

2017-05-02 15:37 UTC, fiddenmar commented on pybico_crf.py
> +				sys.exit(0)
Думаю, нужно реализовать логику программы таким образом, чтобы код добавления записей в базу данных и/или вывода на экран был общим как для считывания одной строки, так и для считывания файла.

2017-05-15 15:01 UTC, fiddenmar commented on pybico_crf.py
>  		opts, args = getopt.getopt(sys.argv[1:], 'hb:u:p:l')
Забыл добавить сам ключ в список возможных аргументов.

2017-05-15 15:43 UTC, fiddenmar approved these changes

2017-05-15 15:45 UTC, merged